repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: pretty-format-json
    args: [--no-ensure-ascii, --autofix]
    files: |
      (?x)^(
        src/MCPServer/lib/assets/.*\.json|
        src/(MCPClient/MCPServer|dashboard)/osdeps/.*\.json
      )
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.5
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
- repo: https://github.com/adamchainz/django-upgrade
  rev: "1.17.0"
  hooks:
  - id: django-upgrade
    args: [--target-version, "4.2"]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.41.0
  hooks:
  - id: markdownlint
    exclude: |
      (?x)^(
        ISSUE_TEMPLATE\.md|
        src/dashboard/(frontend/app|src/media)/vendor/.*
      )
- repo: https://github.com/thlorenz/doctoc
  rev: v2.2.0
  hooks:
  - id: doctoc
    files: |
      (?x)^(
        (CONTRIBUTING|SECURITY).*\.md|
        hack/README\.md|
        src/(MCPServer|MCPClient|dashboard)/install/README\.md
      )
- repo: https://github.com/citation-file-format/cffconvert
  # Current "2.0.0" git tag does not work because of
  # https://github.com/citation-file-format/cffconvert/issues/375
  rev: 054bda51dbe278b3e86f27c890e3f3ac877d616c
  hooks:
    - id: validate-cff
