---

sudo: false
dist: xenial

language: python
cache: pip

git:
  submodules: false

branches:
  only:
    - qa/1.x
    - /^stable\/\d+\.\d+\.x$/

before_script:
  - pip install tox

script: tox

install: true

notifications:
  email: false

matrix:
  fast_finish: true
  include:

    # Dashboard

    - python: "2.7"
      env: TOXENV=py27

    - python: "3.6"
      env: TOXENV=py36

    # MCPServer

    - python: "2.7"
      env: TOXENV=mcpserver

    - python: "3.6"
      env: TOXENV=mcpserver

    # Linters

    - python: "3.7"
      env: TOXENV=linting

    # Dashboard JS

    - language: node_js
      node_js: "8"
      cache: npm
      before_install:
        - cd ./src/dashboard/frontend/
      install: npm install
      before_script:
        - '' # override global before_script
      script: npm run "test-single-run"
      addons:
        chrome: stable

  allow_failures:

    - python: "3.6"
      env: TOXENV=py36

    - python: "3.6"
      env: TOXENV=mcpserver
