name: "Push images to Docker Hub"
#on: workflow_dispatch
on:
  push:
    branches:
      - "dev/trim-dockerfile"
jobs:
  build:
    name: "Build and push images"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up buildx"
        uses: "docker/setup-buildx-action@v3"
        with:
          version: latest
          driver-opts: image=moby/buildkit:v0.13.0
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: artefactual
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: "Build and Push Dashboard"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          load: true
          file: ./hack/Dockerfile
          target: "archivematica-dashboard"
          tags: artefactual/archivematica-dashboard:latest
      - name: "Build and Push MCPClient"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          load: true
          file: ./hack/Dockerfile
          target: "archivematica-mcp-client"
          tags: artefactual/archivematica-mcp-client:latest
      - name: "Build and Push MCPServer"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          load: true
          file: ./hack/Dockerfile
          target: "archivematica-mcp-server"
          tags: artefactual/archivematica-mcp-server:latest
